platform :ios, '13.0'

target 'RxAppleSignIn Example' do
  use_frameworks!
  
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  
  target 'RxAppleSignIn Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
